# -*- coding: utf-8 -*-
"""smartbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zoVguD25KE2qB4Ez5b3b2fQGmkbaFa2B
"""

!pip install transformers
!pip install --upgrade transformers
!pip install transformers==4.11.3

!pip install PyPDF2 docx2txt



import PyPDF2
import docx2txt

def extract_text_from_pdf(file_name):
    with open(file_name, 'rb') as pdf_file:
        pdf_reader = PyPDF2.PdfReader(file_name)

        text = ''
        for page_num in range(pdf_reader.numPages):
            text += pdf_reader.getPage(page_num).extractText()
    return text

def extract_text_from_docx(file_name):
    text = docx2txt.process(file_name)
    return text

def extract_text_from_txt(file_name):
    with open(file_name, 'r', encoding='utf-8') as txt_file:
        text = txt_file.read()
    return text

file_name = input("Enter the file name (including extension): ")

if file_name.lower().endswith('.pdf'):
    text = extract_text_from_pdf(file_name)
elif file_name.lower().endswith('.docx'):
    text = extract_text_from_docx(file_name)
elif file_name.lower().endswith('.txt'):
    text = extract_text_from_txt(file_name)
else:
    text = "Unsupported file format. Please provide a PDF, DOCX, or TXT file."

print("\nExtracted:")
print(text)

user_question = input("Please enter your question: ")

from transformers import pipeline

question_answerer = pipeline("question-answering")
question_answerer(
    question=user_question,
    context=text,
)